# http://wiki.ros.org/amcl#Parameters
# https://robo-marc.github.io/navigation_documents/amcl.html
# overall filter parameters
min_particles: 200
max_particles: 2000
kld_err: 0.05
kld_z: 0.99
update_min_d: 0.1
update_min_a: 0.1
resample_interval: 1
transform_tolerance: 0.2
recovery_alpha_slow: 0.001
recovery_alpha_fast: 0.1
initial_pose_x: 7.0
initial_pose_y: 0.0
initial_pose_a: 1.5708
initial_conv_xx: 0.5
initial_conv_yy: 0.5
initial_conv_aa: 0.5
gui_publish_rate: 10.0
use_map_topic: true
first_map_only : false

# laser model parameters
laser_min_range: -1.0
laser_max_range: 25
laser_max_beams: 30
laser_z_hit: 0.95
laser_z_short: 0.1
laser_z_max: 0.05
laser_z_rand: 0.2
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
laser_likelihood_max_dist: 2.0
laser_model_type: likelihood_field

# odometry model parameters
odom_model_type: diff
odom_alpha1: 5.0
odom_alpha2: 2.0
odom_alpha3: 0.2
odom_alpha4: 0.2
odom_alpha5: 0.2