TARGET_VELOCITY: 0.5
VELOCITY_RESOLUTION: 0.1
YAWRATE_RESOLUTION: 0.05
PREDICT_TIME: 5.0
TO_GOAL_COST_GAIN: 1.4
SPEED_COST_GAIN: 10.0
OBSTACLE_COST_GAIN: 1.0
ANGLE_RESOLUTION: 0.0087
MAX_DIST: 10.0
GOAL_THRESHOLD: 0.3
TURN_DIRECTION_THRESHOLD: 0.1

MAX_VELOCITY: 0.5
MIN_VELOCITY: 0.0
MAX_YAWRATE: 1.50
MAX_D_YAWRATE: 2.4
MAX_ACCELERATION: 1.8
HZ: 10
USE_SCAN_AS_INPUT: true
