LOWER_RED_H: 130
LOWER_RED_S: 180
LOWER_RED_V: 80
UPPER_RED_H: 180
UPPER_RED_S: 230
UPPER_RED_V: 180

LOWER_BLUE_H: 95
LOWER_BLUE_S: 106
LOWER_BLUE_V: 32
UPPER_BLUE_H: 110
UPPER_BLUE_S: 255
UPPER_BLUE_V: 180

LOWER_YELLOW_H: 21
LOWER_YELLOW_S: 100
LOWER_YELLOW_V: 85
UPPER_YELLOW_H: 42
UPPER_YELLOW_S: 210
UPPER_YELLOW_V: 255

LOWER_GREEN_H: 70
LOWER_GREEN_S: 155
LOWER_GREEN_V: 30
UPPER_GREEN_H: 90
UPPER_GREEN_S: 255
UPPER_GREEN_V: 120

LOWER_ORANGE_H: 10
LOWER_ORANGE_S: 125
LOWER_ORANGE_V: 115
UPPER_ORANGE_H: 20
UPPER_ORANGE_S: 200
UPPER_ORANGE_V: 165

LOWER_PURPLE_H: 110
LOWER_PURPLE_S: 80
LOWER_PURPLE_V: 40
UPPER_PURPLE_H: 150
UPPER_PURPLE_S: 230
UPPER_PURPLE_V: 100

LOWER_APRICOT_H: 110
LOWER_APRICOT_S: 80
LOWER_APRICOT_V: 40
UPPER_APRICOT_H: 150
UPPER_APRICOT_S: 230
UPPER_APRICOT_V: 100

LOWER_NAVY_H: 110
LOWER_NAVY_S: 80
LOWER_NAVY_V: 40
UPPER_NAVY_H: 150
UPPER_NAVY_S: 230
UPPER_NAVY_V: 100

LOWER_OLIVE_H: 110
LOWER_OLIVE_S: 80
LOWER_OLIVE_V: 40
UPPER_OLIVE_H: 150
UPPER_OLIVE_S: 230
UPPER_OLIVE_V: 100

LOWER_BROWN_H: 110
LOWER_BROWN_S: 80
LOWER_BROWN_V: 40
UPPER_BROWN_H: 150
UPPER_BROWN_S: 230
UPPER_BROWN_V: 100
