roomba1_whitebalance_threshold: 0.9
roomba2_whitebalance_threshold: 0.9
roomba3_whitebalance_threshold: 0.9
roomba4_whitebalance_threshold: 0.9
roomba5_whitebalance_threshold: 0.9
roomba6_whitebalance_threshold: 0.9
