ROOMBA4_LOWER_RED_H: 130
ROOMBA4_LOWER_RED_S: 95
ROOMBA4_LOWER_RED_V: 0
ROOMBA4_UPPER_RED_H: 180
ROOMBA4_UPPER_RED_S: 230
ROOMBA4_UPPER_RED_V: 180
ROOMBA4_LOWER_BLUE_H: 95
ROOMBA4_LOWER_BLUE_S: 210
ROOMBA4_LOWER_BLUE_V: 40
ROOMBA4_UPPER_BLUE_H: 110
ROOMBA4_UPPER_BLUE_S: 255
ROOMBA4_UPPER_BLUE_V: 180
ROOMBA4_LOWER_YELLOW_H: 20
ROOMBA4_LOWER_YELLOW_S: 160
ROOMBA4_LOWER_YELLOW_V: 70
ROOMBA4_UPPER_YELLOW_H: 40
ROOMBA4_UPPER_YELLOW_S: 210
ROOMBA4_UPPER_YELLOW_V: 255
ROOMBA4_LOWER_GREEN_H: 60
ROOMBA4_LOWER_GREEN_S: 140
ROOMBA4_LOWER_GREEN_V: 10
ROOMBA4_UPPER_GREEN_H: 80
ROOMBA4_UPPER_GREEN_S: 230
ROOMBA4_UPPER_GREEN_V: 100
ROOMBA4_LOWER_ORANGE_H: 0
ROOMBA4_LOWER_ORANGE_S: 1
ROOMBA4_LOWER_ORANGE_V: 0
ROOMBA4_UPPER_ORANGE_H: 0
ROOMBA4_UPPER_ORANGE_S: 0
ROOMBA4_UPPER_ORANGE_V: 0
ROOMBA4_LOWER_PURPLE_H: 115
ROOMBA4_LOWER_PURPLE_S: 115
ROOMBA4_LOWER_PURPLE_V: 0
ROOMBA4_UPPER_PURPLE_H: 135
ROOMBA4_UPPER_PURPLE_S: 150
ROOMBA4_UPPER_PURPLE_V: 75
