ROOMBA5_LOWER_RED_H: 130
ROOMBA5_LOWER_RED_S: 145
ROOMBA5_LOWER_RED_V: 80
ROOMBA5_UPPER_RED_H: 5
ROOMBA5_UPPER_RED_S: 230
ROOMBA5_UPPER_RED_V: 180
ROOMBA5_LOWER_BLUE_H: 95
ROOMBA5_LOWER_BLUE_S: 210
ROOMBA5_LOWER_BLUE_V: 40
ROOMBA5_UPPER_BLUE_H: 110
ROOMBA5_UPPER_BLUE_S: 255
ROOMBA5_UPPER_BLUE_V: 180
ROOMBA5_LOWER_YELLOW_H: 30
ROOMBA5_LOWER_YELLOW_S: 120
ROOMBA5_LOWER_YELLOW_V: 125
ROOMBA5_UPPER_YELLOW_H: 40
ROOMBA5_UPPER_YELLOW_S: 255
ROOMBA5_UPPER_YELLOW_V: 255
ROOMBA5_LOWER_GREEN_H: 60
ROOMBA5_LOWER_GREEN_S: 145
ROOMBA5_LOWER_GREEN_V: 50
ROOMBA5_UPPER_GREEN_H: 90
ROOMBA5_UPPER_GREEN_S: 230
ROOMBA5_UPPER_GREEN_V: 100
ROOMBA5_LOWER_ORANGE_H: 10
ROOMBA5_LOWER_ORANGE_S: 150
ROOMBA5_LOWER_ORANGE_V: 80
ROOMBA5_UPPER_ORANGE_H: 25
ROOMBA5_UPPER_ORANGE_S: 200
ROOMBA5_UPPER_ORANGE_V: 200
ROOMBA5_LOWER_PURPLE_H: 0
ROOMBA5_LOWER_PURPLE_S: 1
ROOMBA5_LOWER_PURPLE_V: 0
ROOMBA5_UPPER_PURPLE_H: 0
ROOMBA5_UPPER_PURPLE_S: 0
ROOMBA5_UPPER_PURPLE_V: 0
