ROOMBA3_LOWER_RED_H: 130
ROOMBA3_LOWER_RED_S: 145
ROOMBA3_LOWER_RED_V: 50
ROOMBA3_UPPER_RED_H: 180
ROOMBA3_UPPER_RED_S: 230
ROOMBA3_UPPER_RED_V: 180
ROOMBA3_LOWER_BLUE_H: 0
ROOMBA3_LOWER_BLUE_S: 1
ROOMBA3_LOWER_BLUE_V: 0
ROOMBA3_UPPER_BLUE_H: 0
ROOMBA3_UPPER_BLUE_S: 0
ROOMBA3_UPPER_BLUE_V: 0
ROOMBA3_LOWER_YELLOW_H: 20
ROOMBA3_LOWER_YELLOW_S: 120
ROOMBA3_LOWER_YELLOW_V: 90
ROOMBA3_UPPER_YELLOW_H: 40
ROOMBA3_UPPER_YELLOW_S: 255
ROOMBA3_UPPER_YELLOW_V: 255
ROOMBA3_LOWER_GREEN_H: 60
ROOMBA3_LOWER_GREEN_S: 100
ROOMBA3_LOWER_GREEN_V: 45
ROOMBA3_UPPER_GREEN_H: 90
ROOMBA3_UPPER_GREEN_S: 230
ROOMBA3_UPPER_GREEN_V: 100
ROOMBA3_LOWER_ORANGE_H: 10
ROOMBA3_LOWER_ORANGE_S: 115
ROOMBA3_LOWER_ORANGE_V: 90
ROOMBA3_UPPER_ORANGE_H: 20
ROOMBA3_UPPER_ORANGE_S: 200
ROOMBA3_UPPER_ORANGE_V: 200
ROOMBA3_LOWER_PURPLE_H: 125
ROOMBA3_LOWER_PURPLE_S: 80
ROOMBA3_LOWER_PURPLE_V: 10
ROOMBA3_UPPER_PURPLE_H: 150
ROOMBA3_UPPER_PURPLE_S: 230
ROOMBA3_UPPER_PURPLE_V: 50
