# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
# This example is compatible with Dynamixel using protocol 2.0

dynamixel:
    ID: 1
    Return_Delay_Time: 0
    Operating_Mode: 3
    Profile_Acceleration: 0
    Profile_Velocity: 0
    LED: 1
    Homing_Offset: -270


dynamixel:
    ID: 11
    Return_Delay_Time: 0
    Operating_Mode: 3
    Profile_Acceleration: 0
    Profile_Velocity: 0
    LED: 1
    Homing_Offset: 495

dynamixel:
    ID: 12
    Return_Delay_Time: 0
    Operating_Mode: 3
    Profile_Acceleration: 0
    Profile_Velocity: 0
    LED: 1
    Homing_Offset: -150

dynamixel:
    ID: 13
    Return_Delay_Time: 0
    Operating_Mode: 3
    Profile_Acceleration: 0
    Profile_Velocity: 0
    LED: 1
    Homing_Offset: 1024

dynamixel:
    ID: 14
    Return_Delay_Time: 0
    Operating_Mode: 3
    Profile_Acceleration: 0
    Profile_Velocity: 0
    LED: 1
    Homing_Offset: -70

dynamixel:
    ID: 15
    Return_Delay_Time: 0
    Operating_Mode: 3
    Profile_Acceleration: 0
    Profile_Velocity: 0
    LED: 1
    Homing_Offset: -203

dynamixel:
    ID: 16
    Return_Delay_Time: 0
    Operating_Mode: 3
    Profile_Acceleration: 0
    Profile_Velocity: 0
    LED: 1
    Homing_Offset: -403

