relation0: [15, 1]
relation1: [0, 2]
relation2: [1, 3]
relation3: [15, 7, 4]
relation4: [3, 5]
relation5: [4, 6]
relation6: [5, 7]
relation7: [3, 11, 8]
relation8: [7, 9]
relation9: [8, 10]
relation10: [9, 11]
relation11: [12, 15, 7]
relation12: [13, 11]
relation13: [14, 12]
relation14: [13, 15]
relation15: [0, 3, 11]